name: cypress test run report

on:
    push:
        branches:
            - feature/*
            - develop
jobs:
    cypress-test:
        name: Run e2e tests
        runs-on: ubuntu-latest
        container: 
          image: cypress/browsers:node16.17.0-chrome106
          options: --user 1001
        environment: DEV
        steps:
            - uses: actions/checkout@v2

            - name: Download Cypress
              continue-on-error: true
              run: |
                npm ci

            - name: Start react app and run cypress tests
              continue-on-error: true
              run: npx cypress run --env MAILSLURP_API_KEY=${{ secrets.MAILSLURP_API_KEY }} --browser chrome